07/23/2024 05:44:25 - INFO: Loading 200 samples from KITTI_2015 dataset.
  0%|          | 0/200 [00:00<?, ?it/s]/home/ma/ma_ma/ma_xinygao/miniconda3/envs/pcfa/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at /opt/conda/conda-bld/pytorch_1708025831440/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
  0%|          | 0/200 [00:09<?, ?it/s]

-------------------------------------------------------------------------------
attacks.py 1361 <module>
attack(args, model)

attacks.py 675 attack
metrics_mean, iteration_metrics_mean = attack_one_dataloader(

_contextlib.py 115 decorate_context
return func(*args, **kwargs)

attacks.py 918 attack_one_dataloader
preds, perturbed_inputs = common_corrupt(attack_args, inputs, model)

common_corruptions.py 47 common_corrupt
image_1_corrupt = corrupt(

__init__.py 61 corrupt
image_corrupted = corruption_dict[corruption_name](Image.fromarray(image),

corruptions.py 198 glass_blur
gaussian(np.array(x) / 255., sigma=c[0], multichannel=True) * 255)

utils.py 321 fixed_func
return func(*args, **kwargs)

TypeError:
gaussian() got an unexpected keyword argument 'multichannel'
